ClientSystem/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from . import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', views.index),
    path('detail/<int:id>', views.detail),
    re_path(r'^students/(?P<year>\d{4})-(?P<month>\d[1-9]|1[0-2])/$', views.student_list),
    # path('teacher/', include('teacher.urls'),kwargs={'args': 'something'}),
    path('teacher/', include('teacher.urls')),
    path('student/', include('student.urls')),
]

student/urls.py
#!/usr/bin/python3 
# encoding: utf-8 

"""
@version: v1.0
@author: ligui
@contact: 1947346653@qq.com
@software: PyCharm
@file: urls.py
@time: 2022/11/4 14:42
"""

from django.urls import path
from . import views

app_name = 'student'
urlpatterns = [
    path('students/', views.students, name='students'),
    path('add/', views.student_add, name="add"),
    path('delete/<pk>', views.student_delete, name="delete"),
    path('detail/<pk>', views.student_detail, name="detail"),
    path('edit/<pk>', views.student_edit, name="edit"),
    path('login/', views.login_view, name='student_login'),
    path('logout/', views.logout_view, name='student_logout'),
    path('register/', views.register, name='register'),
    path('detail_form_edit/<pk>', views.form_edit, name='detail_form_edit'),
    path('detail_form_add/', views.form_add, name='detail_form_add'),
]

student/models.py
from django.db import models


# Create your models here.
class Student(models.Model):
    name = models.CharField("学生姓名", max_length=20)
    age = models.SmallIntegerField("年龄")
    sex = models.SmallIntegerField(default=1)
    qq = models.CharField(max_length=20, unique=True, error_messages={'unique': 'qq号码已被使用'})
    phone = models.CharField(max_length=20, unique=True)
    create_time = models.DateTimeField("创建时间", auto_now_add=True)
    update_time = models.DateTimeField("修改时间", auto_now=True)
    grade = models.ForeignKey("Grade", on_delete=models.SET_NULL, null=True)
    is_delete = models.BooleanField(default=False)


class StudentDetail(models.Model):
    num = models.CharField('身份证', unique=True, max_length=40, default='')
    college = models.CharField('毕业学校', max_length=20, default='')
    student = models.OneToOneField('Student', related_name='detail', on_delete=models.CASCADE)


class Grade(models.Model):
    name = models.CharField('班级名称', max_length=20)
    num = models.CharField('班期', max_length=20)

    def __str__(self):
        return self.name + '-' + self.num


class Course(models.Model):
    name = models.CharField("课程名称", max_length=20)
    students = models.ManyToManyField('Student', through='Enroll')


class Enroll(models.Model):
    student = models.ForeignKey('Student', on_delete=models.CASCADE)
    course = models.ForeignKey('Course', on_delete=models.CASCADE)
    create_time = models.DateTimeField("创建时间", auto_now_add=True)

student/forms.py
from django import forms

from student.models import Student, StudentDetail


class LoginForm(forms.Form):
    username = forms.CharField(label='用户名', max_length=20)
    password = forms.CharField(label='密码',
                               max_length=15,
                               min_length=4,
                               widget=forms.PasswordInput(attrs={
                                   'placeholder': '请输入长度为0-15位的密码'
                               }),
                               error_messages={
                                   'max_length': '密码长度大于15位',
                                   'min_length': '密码长度小于6位',
                               }
                               )


class RegisterForm(forms.Form):
    username = forms.CharField(label='用户名', max_length=20)
    password = forms.CharField(label='密码',
                               max_length=15,
                               min_length=6,
                               widget=forms.PasswordInput(attrs={
                                   'placeholder': '请输入长度为0-15位的密码'
                               }),
                               error_messages={
                                   'max_length': '密码长度大于15位',
                                   'min_length': '密码长度小于6位',
                               }
                               )
    password_repeat = forms.CharField(label='再次输入密码',
                                      widget=forms.PasswordInput()
                                      )
    email = forms.EmailField(required=False)

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        password_repeat = cleaned_data.get('password_repeat')

        if password != password_repeat:
            msg = '密码不一致'
            self.add_error(password_repeat, msg)


class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        exclude = ['is_delete']


class StudentDetailForm(forms.ModelForm):
    class Meta:
        model = StudentDetail
        exclude = ['student']

    def clean_num(self):
        data = self.cleaned_data.get('num')
        if not data[:-1].isdigit():
            self.add_error('num', '您输入的身份证号码格式有误')
            # raise forms.ValidationError('您输入的身份证号码格式有误')
        return data

student/views.py
from django.contrib.auth import authenticate, login, logout
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import render, reverse, redirect

from student.forms import StudentForm, StudentDetailForm, RegisterForm
from student.models import Student, Grade, StudentDetail
from django.contrib.auth.decorators import login_required, permission_required
from django.core.paginator import Paginator
import math


# Create your views here.
def students(request):
    section = "学生列表"
    search = request.GET.get('search')
    name = request.session.get('name')
    print(search)
    if search:
        search = search.strip()
        if search.isdigit():
            all_students = Student.objects.filter(Q(qq=search) | Q(phone=search), is_delete=False)
        else:
            all_students = Student.objects.filter(name=search, is_delete=False)
            print(all_students)
    else:
        all_students = Student.objects.filter(is_delete=False)

    all_students = all_students.order_by('-create_time')

    # 实现分页
    # 1.数据总数
    total_num = all_students.count()
    # 2.每页数据条数
    per_page = request.GET.get('per_page', 5)
    # 3.当前页码
    page = request.GET.get('page', 1)

    paginator = Paginator(all_students, per_page)

    all_students = paginator.get_page(page)

    return render(request, 'student/index.html', context={
        'section': section,
        'students': all_students,
        'page': page,
        'total_page': math.ceil(total_num / int(per_page)),
        'per_page': per_page,
        'name': name
    })


def student_add(request):
    if not request.user.has_perm('student.add_student'):
        return HttpResponse('你没有权限添加')
    section = "学生信息添加"
    if request.method == 'POST':
        try:
            message = request.POST
            data = {
                'name': message.get('username'),
                'age': message.get('age'),
                'qq': message.get('qq'),
                'sex': message.get('sex'),
                'phone': message.get('phone'),
                'grade_id': message.get('grade'),
            }
            num = message.get('num')
            college = message.get('college')
            s = Student.objects.create(**data)
            StudentDetail.objects.create(num=num, college=college, student=s)
            return redirect(reverse('student:students'))
        except Exception as e:
            return HttpResponse(e)
    # grades = Grade.objects.all()
    return render(request, 'student/detail.html', context={
        'section': section,
        # 'grades': grades
    })


def student_delete(request, pk):
    student = Student.objects.get(id=pk)
    student.is_delete = True
    student.save()
    return redirect(reverse('student:students'))


@login_required()
def student_detail(request, pk):
    # if not request.user.is_authenticated:
    #     return redirect(reverse('student:student_login') + f'?next={request.path}')
    section = "学生信息查询"
    student = Student.objects.get(id=pk)
    # grades = Grade.objects.all()
    return render(request, 'student/detail.html', context={
        'section': section,
        'student': student,
        # 'grades': grades
    })


def student_edit(request, pk):
    section = '学生信息编辑'
    # grades = Grade.objects.all()
    student = Student.objects.get(pk=pk)
    if request.method == 'POST':
        try:
            message = request.POST
            data = {
                'name': message.get('username'),
                'age': message.get('age'),
                'qq': message.get('qq'),
                'sex': message.get('sex'),
                'phone': message.get('phone'),
            }
            grade_id = message.get('grade')
            try:
                grade = Grade.objects.get(id=grade_id)
            except:
                grade = None
            try:
                s_detail = student.detail
            except:
                s_detail = StudentDetail()
                s_detail.student = student
            num = message.get('num')
            college = message.get('college')
            s_detail.num = num
            s_detail.college = college
            s_detail.save()
            Student.objects.filter(pk=pk).update(**data, grade=grade)
            return redirect(reverse('student:students'))
        except Exception as e:
            print(e)
            return HttpResponse(e)

    return render(request, 'student/detail.html', context={
        'section': section,
        # 'grades': grades,
        'student': student
    })


def form_edit(request, pk):
    student = Student.objects.get(pk=pk)
    section = '学生信息编辑'
    form = StudentForm(instance=student)
    detail_form = StudentDetailForm(instance=student.detail)
    if request.method == 'POST':
        form = StudentForm(request.POST, instance=student)
        try:
            detail_form = StudentDetailForm(request.POST, instance=student.detail)
        except:
            student_detail = StudentDetail()
            student_detail.student = student
            student_detail.save()
            detail_form = StudentDetailForm(request.POST, instance=student.detail)

        if form.is_valid() and detail_form.is_valid():
            form.save()
            detail_form.save()
            return redirect(reverse('student:students'))

    return render(request, 'student/form_detail.html', context={
        'form': form,
        'detail_form': detail_form,
        'section': section
    })


@permission_required('student.add_student', raise_exception=True)
def form_add(request):
    # if not request.user.has_perm('student.add_student'):
    #     return HttpResponse('你没有权限添加')
    section = '学生信息添加'
    form = StudentForm()
    detail_form = StudentDetailForm()

    if request.method == 'POST':
        form = StudentForm(request.POST)
        if form.is_valid():
            form.save()

        student = Student.objects.last()
        # student = Student.objects.get(qq=form.cleaned_data.get('qq'))
        try:
            detail_form = StudentDetailForm(request.POST, instance=student.detail)
        except:
            student_detail = StudentDetail()
            student_detail.student = student
            student_detail.save()
            detail_form = StudentDetailForm(request.POST, instance=student.detail)

        if form.is_valid() and detail_form.is_valid():
            form.save()
            detail_form.save()
            return redirect(reverse('student:students'))

    return render(request, 'student/form_detail.html', context={
        'section': section,
        'form': form,
        'detail_form': detail_form
    })


# def login(request):
#     if request.method == 'POST':
#         username = request.POST.get('username')
#         password = request.POST.get('password')
#
#         if username == 'feifei' and password == 'feifei':
#             # 将用户名保存到session
#             request.session['name'] = username
#             request.session.set_expiry(10)
#             return redirect(reverse('student:students'))
#     return render(request, 'student/login.html')

def login_view(request):
    next_url = request.GET.get('next')
    if request.user.is_authenticated:
        if next_url:
            return redirect(next_url)
        return redirect(reverse('student:students'))
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        # 校验用户名和密码
        user = authenticate(username=username, password=password)
        if user:
            # 将用户名保存到session
            login(request, user)
            if next_url:
                return redirect(next_url)
            return redirect(reverse('student:students'))

    return render(request, 'student/login.html')


# def logout(request):
#     request.session.flush()
#     return redirect(reverse('student:students'))

def logout_view(request):
    logout(request)
    return redirect(reverse('student:students'))


def register(request):
    if request.method == 'GET':
        form = RegisterForm()
    elif request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            password = form.cleaned_data.get('password')
            password_repeat = form.cleaned_data.get('password_repeat')
            if password_repeat != password:
                return HttpResponse('注册成功')
    return render(request, 'student/register.html', context={
        'form': form
    })

templates/student/base.html
<!doctype html>
<html lang="zh-CN">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="https://fastly.jsdelivr.net/npm/@bootcss/v3.bootcss.com@1.0.32/favicon.ico">
    <link rel="canonical" href="https://getbootstrap.com/docs/3.4/examples/dashboard/">

    <title>{% block title %}Dashboard Template for Bootstrap{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="https://fastly.jsdelivr.net/npm/@bootcss/v3.bootcss.com@1.0.32/dist/css/bootstrap.min.css"
          rel="stylesheet">
    {% block link %}{% endblock %}

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="https://fastly.jsdelivr.net/npm/@bootcss/v3.bootcss.com@1.0.32/assets/css/ie10-viewport-bug-workaround.css"
          rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="https://fastly.jsdelivr.net/npm/@bootcss/v3.bootcss.com@1.0.32/examples/dashboard/dashboard.css"
          rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]>
    <script src="https://fastly.jsdelivr.net/npm/@bootcss/v3.bootcss.com@1.0.32/assets/js/ie8-responsive-file-warning.js"></script>
    <![endif]-->
    <script src="https://fastly.jsdelivr.net/npm/@bootcss/v3.bootcss.com@1.0.32/assets/js/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>

<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">CRM管理系统</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                <li><a href="#">{% block login %}学生论坛{% endblock %}</a></li>
                <li><a href="#">设置</a></li>
                <li><a href="#">帮助</a></li>
            {% block loginOrlogout %}
                <li><a href="#">退出</a></li>
            {% endblock %}
            </ul>
        </div>
    </div>
</nav>

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
            <ul class="nav nav-sidebar">
                <li><a href="">学生展示</a></li>
                <li><a href="">学生管理</a></li>
                <li><a href="">班级管理</a></li>
                <li><a href="">课程管理</a></li>
            </ul>
            <ul class="nav nav-sidebar">
                <li><a href="">订单管理</a></li>
                <li><a href="">系统设置</a></li>
                <li><a href="">菜单设置</a></li>
                <li><a href="">权限管理</a></li>
            </ul>
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">

            <h2 class="sub-header">{% block section %}Section title{% endblock %}</h2>
            {% block search %}{% endblock %}
        {% block content %}
            <div class="table-responsive">

                    <table class="table table-striped">

                        <thead>
                        <tr>
                            <th>#</th>
                            <th>Header</th>
                            <th>Header</th>
                            <th>Header</th>
                            <th>Header</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td>序号</td>
                            <td>姓名</td>
                            <td>年龄</td>
                            <td>性别</td>
                            <td>qq号码</td>
                            <td>电话号码</td>
                        </tr>

                        <tr>
                            <td>1,002</td>
                            <td>amet</td>
                            <td>consectetur</td>
                            <td>adipiscing</td>
                            <td>elit</td>
                        </tr>
                        <tr>
                            <td>1,003</td>
                            <td>Integer</td>
                            <td>nec</td>
                            <td>odio</td>
                            <td>Praesent</td>
                        </tr>
                        <tr>
                            <td>1,003</td>
                            <td>libero</td>
                            <td>Sed</td>
                            <td>cursus</td>
                            <td>ante</td>
                        </tr>
                        <tr>
                            <td>1,004</td>
                            <td>dapibus</td>
                            <td>diam</td>
                            <td>Sed</td>
                            <td>nisi</td>
                        </tr>
                        <tr>
                            <td>1,005</td>
                            <td>Nulla</td>
                            <td>quis</td>
                            <td>sem</td>
                            <td>at</td>
                        </tr>
                        <tr>
                            <td>1,006</td>
                            <td>nibh</td>
                            <td>elementum</td>
                            <td>imperdiet</td>
                            <td>Duis</td>
                        </tr>
                        <tr>
                            <td>1,007</td>
                            <td>sagittis</td>
                            <td>ipsum</td>
                            <td>Praesent</td>
                            <td>mauris</td>
                        </tr>
                        <tr>
                            <td>1,008</td>
                            <td>Fusce</td>
                            <td>nec</td>
                            <td>tellus</td>
                            <td>sed</td>
                        </tr>
                        <tr>
                            <td>1,009</td>
                            <td>augue</td>
                            <td>semper</td>
                            <td>porta</td>
                            <td>Mauris</td>
                        </tr>
                        <tr>
                            <td>1,010</td>
                            <td>massa</td>
                            <td>Vestibulum</td>
                            <td>lacinia</td>
                            <td>arcu</td>
                        </tr>
                        <tr>
                            <td>1,011</td>
                            <td>eget</td>
                            <td>nulla</td>
                            <td>Class</td>
                            <td>aptent</td>
                        </tr>
                        <tr>
                            <td>1,012</td>
                            <td>taciti</td>
                            <td>sociosqu</td>
                            <td>ad</td>
                            <td>litora</td>
                        </tr>
                        <tr>
                            <td>1,013</td>
                            <td>torquent</td>
                            <td>per</td>
                            <td>conubia</td>
                            <td>nostra</td>
                        </tr>
                        <tr>
                            <td>1,014</td>
                            <td>per</td>
                            <td>inceptos</td>
                            <td>himenaeos</td>
                            <td>Curabitur</td>
                        </tr>
                        <tr>
                            <td>1,015</td>
                            <td>sodales</td>
                            <td>ligula</td>
                            <td>in</td>
                            <td>libero</td>
                        </tr>
                        </tbody>
                    </table>

            </div>
        {% endblock %}
        </div>
    </div>
</div>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://fastly.jsdelivr.net/npm/jquery@1.12.4/dist/jquery.min.js"
        integrity="sha384-nvAa0+6Qg9clwYCGGPpDQLVpLNn0fRaROjHqs13t4Ggj3Ez50XnGQqc/r8MhnRDZ"
        crossorigin="anonymous"></script>
<script>window.jQuery || document.write('<script src="https://fastly.jsdelivr.net/npm/@bootcss/v3.bootcss.com@1.0.32/assets/js/vendor/jquery.min.js"><\/script>')</script>
<script src="https://fastly.jsdelivr.net/npm/@bootcss/v3.bootcss.com@1.0.32/dist/js/bootstrap.min.js"></script>
<!-- Just to make our placeholder images work. Don't actually copy the next line! -->
<script src="https://fastly.jsdelivr.net/npm/@bootcss/v3.bootcss.com@1.0.32/assets/js/vendor/holder.min.js"></script>
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script src="https://fastly.jsdelivr.net/npm/@bootcss/v3.bootcss.com@1.0.32/assets/js/ie10-viewport-bug-workaround.js"></script>
</body>
</html>

templates/student/detail.html
{% extends 'student/base.html' %}
{% load customerTags %}
{% block section %}{{ section }}{% endblock %}
{% block login %}欢迎{{ name }}登陆{% endblock %}
{#{% block loginOrlogout %}#}
{#    {% if request.session.name %}#}
{#        <li><a href="{% url 'students:student_logout' %}">退出登陆</a></li>#}
{#    {% else %}#}
{#        <li><a href="{% url 'students:student_login' %}">登陆</a></li>#}
{#    {% endif %}#}
{#{% endblock %}#}
{% load customerFilters %}
{% block content %}
    <form class="form-horizontal" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="username" class="col-sm-2 control-label">姓名</label>
            <div class="col-sm-2">
                <input type="text" name="username" class="form-control" id="username" placeholder="请输入您的姓名"
                       value="{{ student.name }}">
            </div>
        </div>
        <div class="form-group">
            <label for="age" class="col-sm-2 control-label">年龄</label>
            <div class="col-sm-2">
                <input type="text" name="age" class="form-control" id="age" placeholder="请输入您的年龄"
                       value="{{ student.age }}">
            </div>
        </div>
        <div class="form-group">
            <label for="age" class="col-sm-2 control-label">性别</label>
            <div class="col-sm-2">
                <input type="radio" name="sex" value="1" {% if student.sex == 1 %}checked{% endif %}> 男
                <input type="radio" name="sex" value="0" {% if student.sex == 0 %}checked{% endif %}> 女
            </div>
        </div>
        <div class="form-group">
            <label for="qq" class="col-sm-2 control-label">qq</label>
            <div class="col-sm-3">
                <input type="text" name="qq" class="form-control" id="qq" placeholder="请输入您的qq" value="{{ student.qq }}">
            </div>
        </div>
        <div class="form-group">
            <label for="phone" class="col-sm-2 control-label">电话</label>
            <div class="col-sm-3">
                <input type="text" name="phone" class="form-control" placeholder="请输入您的电话" id="phone" value="{{ student.phone }}">
            </div>
        </div>
        <div class="form-group">
            <label for="num" class="col-sm-2 control-label">身份证</label>
            <div class="col-sm-4">
                <input type="text" name="num" class="form-control" id="num" placeholder="请输入您的身份证" value="{% if not student.detail.num == '' %}{{ student.detail.num }}{% else %}信息待补充{% endif %}">
            </div>
        </div>
        <div class="form-group">
            <label for="college" class="col-sm-2 control-label">院校</label>
            <div class="col-sm-2">
                <input type="text" name="college" class="form-control" id="college"
                       value="{% if not student.detail.college == '' %}{{ student.detail.college }}{% else %}信息待补充{% endif %}">
            </div>
        </div>
        <div class="form-group">
            <label for="grade" class="col-sm-2 control-label">分班</label>
            <div class="col-sm-2">
{#                <select class="form-control">#}
{#                    <option>{{ student.grade }}</option>#}
{#                    {% for grade in grades %}#}
{#                    <option>{{ grade }}</option>#}
{#                    {% endfor %}#}
{#                </select>#}
{#                {% college student %}#}
                {% show_class student %}
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                {% if section == '学生信息添加' or section == '学生信息编辑' %}
                    <button type="submit" class="btn btn-success">保存</button>
                    <button type="reset" class="btn btn-default">重置</button>
                {% elif section == '学生信息查询' %}
                    <a href="{% url 'student:students' %}" class="btn btn-info">返回</a>{% endif %}
            </div>
        </div>
    </form>
{% endblock %}

templates/student/index.html
{% extends 'student/base.html' %}
{% load static %}
{% load customerFilters %}
{% load customerTags %}
{% block section %}{{ section }}{% endblock %}
{% block title %}首页面{% endblock %}
{% block login %}欢迎{{ user.username|default:'游客' }}{% endblock %}
{% block loginOrlogout %}
    {% if user.is_authenticated %}
        <li><a href="{% url 'student:student_logout' %}">退出</a></li>
    {% else %}
        <li><a href="{% url 'student:student_login' %}">登陆</a></li>
    {% endif %}
{% endblock %}
{% block search %}
    <div class="row">
        <form class="navbar-form navbar-left" role="search">
            <div class="form-group">
                <input type="text" class="form-control" placeholder="请输入你要查找的学生姓名，qq或电话" name="search">
            </div>
            <button type="submit" class="btn btn-primary">搜索</button>
            <button type="submit" class="btn btn-info">重置</button>
            {% if perms.student %}<a href="{% url 'student:detail_form_add' %}" class="btn btn-danger">添加</a>{% endif %}
        </form>
    </div>
{% endblock %}
{% block content %}
    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
            <tr>
                <th>序号</th>
                <th>姓名</th>
                <th>年龄</th>
                <th>性别</th>
                <th>qq号码</th>
                <th>电话号码</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>
            {% for student in students %}
                <tr>
                    <td><a href="{% url 'student:detail' student.id %}">{{ student.id }}</a></td>
                    <td>{{ student.name }}</td>
                    <td>{{ student.age }}</td>
                    <td>{{ student.sex|to_sex }}</td>
                    <td>{{ student.qq }}</td>
                    <td>{{ student.phone }}</td>
                    <td>
                        <a href="{% url 'student:detail_form_edit' student.id %}" type="submit" class="btn btn-info btn-xs">编辑</a>
                        <a href="{% url 'student:delete' student.id %}" class="btn btn-danger btn-xs">删除</a>
                    </td>
                </tr>
            {% endfor %}

            </tbody>
        </table>

    </div>
    <div class="btn-group row" role="group" aria-label="..." style="display: flex">
        <nav aria-label="Page navigation">
            <!--自定义包含标签实现分页展示-->
            {% pagination_html %}
        </nav>

        <div class="btn-group" role="group" style="margin-top: 20px;">
            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true"
                    aria-expanded="false">
                {{ per_page }}条/页
                <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" style="margin-top: -26px; min-width: 102px">
                <li><a href="{{ request.path }}?per_page=2">2条/页</a></li>
                <li><a href="{{ request.path }}?per_page=5">5条/页</a></li>
                <li><a href="{{ request.path }}?per_page=10">10条/页</a></li>
            </ul>
        </div>
    </div>
{% endblock %}


templates/student/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="post">
    {{ form.as_p }}
    <input type="submit" value="注册">
</form>
</body>
</html>

templates/student/show_class.html
<select name="grade" class="form-control">
    <option value="0"></option>
    {% for grade in grades %}
        <option value="{{ grade.id }}"{% if grade.id == student.grade_id %}selected{% endif %}>{{ grade }}</option>
    {% endfor %}
</select>