ClientSystem/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from . import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', views.index),
    path('detail/<int:id>', views.detail),
    re_path(r'^students/(?P<year>\d{4})-(?P<month>\d[1-9]|1[0-2])/$', views.student_list),
    # path('teacher/', include('teacher.urls'),kwargs={'args': 'something'}),
    path('teacher/', include('teacher.urls')),
    path('student/', include('student.urls')),
]

student/urls.py
#!/usr/bin/python3 
# encoding: utf-8 

"""
@version: v1.0
@author: ligui
@contact: 1947346653@qq.com
@software: PyCharm
@file: urls.py
@time: 2022/11/4 14:42
"""

from django.urls import path
from . import views

app_name = 'student'
urlpatterns = [
    path('students/', views.students, name='students'),
    path('add/', views.student_add, name="add"),
    path('delete/<pk>', views.student_delete, name="delete"),
    path('detail/<pk>', views.student_detail, name="detail"),
    path('edit/<pk>', views.student_edit, name="edit"),
    path('login/', views.login_view, name='student_login'),
    path('logout/', views.logout_view, name='student_logout'),
    path('register/', views.register, name='register'),
    path('detail_form_edit/<pk>', views.form_edit, name='detail_form_edit'),
    path('detail_form_add/', views.form_add, name='detail_form_add'),
]

teacher/urls.py
#!/usr/bin/python3 
# encoding: utf-8 

"""
@version: v1.0
@author: ligui
@contact: 1947346653@qq.com
@software: PyCharm
@file: urls.py
@time: 2022/11/4 14:20
"""
from django.urls import path
from . import views

app_name = 'teacher'
urlpatterns = [
    path('index/', views.index, name='index'),
    path('students/', views.students, kwargs={'args': 'something'}),
    path('test/', views.students,kwargs={'args': 'something'}),
    path('login/', views.login),
    path('detail/<name>', views.detail, name="detail"),
    path('upload', views.upload_files, name="upload")
]

teacher/models.py
from django.db import models


# Create your models here.
class Student(models.Model):
    name = models.CharField(max_length=20, verbose_name="学生姓名", unique=True)  # 学生姓名
    age = models.SmallIntegerField(null=True)
    sex = models.SmallIntegerField(default=1)  # 设置默认值
    qq = models.CharField(max_length=20, null=True)
    phone = models.CharField(max_length=20, verbose_name="电话", null=True)
    create_time = models.DateTimeField(auto_now_add=True, verbose_name="创建时间")  # 创建时间
    update_time = models.DateTimeField(auto_now=True, verbose_name="更新时间")
    # detail = models.OneToOneField('StudentDetail', on_delete=models.SET_NULL, null=True)  # 一对一对应学生详情表，设置为空删除
    grade = models.ForeignKey('Grade', on_delete=models.SET_NULL, null=True, related_name='student')

    def __str__(self):
        return self.name

    # class Meta:
    #     db_table = "student"


class StudentDetail(models.Model):
    college = models.CharField(verbose_name="学院名", max_length=20, default='')
    student = models.OneToOneField('Student', on_delete=models.CASCADE)

    def __str__(self):
        return self.college


class Grade(models.Model):
    name = models.CharField(verbose_name="班级名称", max_length=20)
    num = models.CharField(verbose_name='班期', max_length=20)

    def __str__(self):
        return self.name + '-' + self.num


class Course(models.Model):
    name = models.CharField(verbose_name="课程名称", max_length=20)
    students = models.ManyToManyField('Student', through='Enroll')

    def __str__(self):
        return self.name

class Enroll(models.Model):
    student = models.ForeignKey('Student', on_delete=models.CASCADE)
    course = models.ForeignKey('Course', on_delete=models.CASCADE)
    c_time = models.DateTimeField('选课时间', auto_now_add=True)

teacher/views.py
import os
from datetime import datetime

from django.shortcuts import render, redirect, reverse
from django.http import HttpResponse
from django.template.loader import get_template

from ClientSystem.settings import MEDIA_ROOT
from .models import Student
from datetime import datetime


# Create your views here.

def index(request):
    """
    t = get_template('teacher/index.html')
    html = t.render()
    return HttpResponse(html)
    """
    students = Student.objects.all()
    num = request.COOKIES.get('num')
    if num:
        num = 1 + int(num)
    else:
        num = 1
    lt = [1, 2, 3]
    dt = {'name': "钟灵珠", 'age': 18, 'sex': 0}
    # students = [
    #     {'name': "钟灵珠", 'age': 19, 'sex': 1, 'id': 0, 'course': ['python', 'English', 'java', 'Sport']},
    #     {'name': "的说法", 'age': 185, 'sex': 0, 'id': 1, 'course': ['python', 'English', 'java', 'Sport']},
    #     {'name': "范德萨个", 'age': 138, 'sex': 1, 'id': 2, 'course': ['python', 'English', 'java', 'Sport']},
    #     {'name': "的撒个", 'age': 182, 'sex': 0, 'id': 3, 'course': ['python', 'English', 'java', 'Sport']},
    # ]
    now = datetime.now()
    # now = now.strftime("%Y年%m月%d日  %H:%M:%S")
    js = '<script>alert("跨域脚本攻击")</script>'

    def func():
        return "something"

    response = render(request, 'teacher/index.html', context={
        'now': now,
        'lt': lt,
        'dt': dt,
        'func': func,
        'js': js,
        'students': students,
        'format_str': '%Y年%m月%d日  %H:%M:%S',
        'num': num
    })
    response.set_cookie('num', num)
    return response
    # return render(request, 'teacher/index_new.html')


def students(request, args):
    return HttpResponse(f"额外参数{args}")


def test(request, args):
    return HttpResponse(f"额外参数{args}")


def login(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        return redirect('teacher:index')
    return render(request, 'teacher/login.html')


def detail(request, name):
    return HttpResponse(f'这是{name}同学的详情')

def upload_files(request):
    if request.method == "POST":
        files = request.FILES.getlist('file')

        # 保存文件
        # 每天上传的文件放入每天的文件夹
        day_dir_name = datetime.now().strftime('%Y-%m-%d')
        day_dir = os.path.join(MEDIA_ROOT, day_dir_name)
        if not os.path.exists(day_dir):
            os.mkdir(day_dir)

        # 保存文件
        for file in files:
            filename = os.path.join(day_dir, file.name)
            with open(filename, 'wb') as  fb:
                for line in file.chunks():  # 上传文件时，会自动分块
                    fb.write(line)
    return render(request, 'teacher/upload.html')

templates/teacher/ad.html
{%  load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>广告</title>
    <link rel="stylesheet" href="{% static 'teacher/css/ad.css' %}">
</head>
<body>
    <h1>此为一个广告</h1>
</body>
</html>

templates/teacher/base.html

<!doctype html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="https://fastly.jsdelivr.net/npm/@bootcss/v3.bootcss.com@1.0.30/favicon.ico">
    <link rel="canonical" href="https://getbootstrap.com/docs/3.4/examples/starter-template/">
    {% block link %}{% endblock %}
    <title>{% block tilte %}{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="https://fastly.jsdelivr.net/npm/@bootcss/v3.bootcss.com@1.0.30/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="https://fastly.jsdelivr.net/npm/@bootcss/v3.bootcss.com@1.0.30/assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="https://fastly.jsdelivr.net/npm/@bootcss/v3.bootcss.com@1.0.30/examples/starter-template/starter-template.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="https://fastly.jsdelivr.net/npm/@bootcss/v3.bootcss.com@1.0.30/assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="https://fastly.jsdelivr.net/npm/@bootcss/v3.bootcss.com@1.0.30/assets/js/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Project name</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="#">Home</a></li>
            <li><a href="#">About</a></li>
            <li><a href="#">Contact</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    {% block content %}{% endblock %}

    <div class="container">

      <div class="starter-template">
        <h1>Bootstrap starter template</h1>
        <p class="lead">Use this document as a way to quickly start any new project.<br> All you get is this text and a mostly barebones HTML document.</p>
      </div>

    </div><!-- /.container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://fastly.jsdelivr.net/npm/jquery@1.12.4/dist/jquery.min.js" integrity="sha384-nvAa0+6Qg9clwYCGGPpDQLVpLNn0fRaROjHqs13t4Ggj3Ez50XnGQqc/r8MhnRDZ" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="https://fastly.jsdelivr.net/npm/@bootcss/v3.bootcss.com@1.0.30/assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="https://fastly.jsdelivr.net/npm/@bootcss/v3.bootcss.com@1.0.30/dist/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="https://fastly.jsdelivr.net/npm/@bootcss/v3.bootcss.com@1.0.30/assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>

templates/teacher/index.html
{% load static %}
{% load customer_filters %}
{% load customer_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>首页面</title>
{#    <link rel="stylesheet" href="/static/teacher/index.css" >#}
    <link rel="stylesheet" href="{% static 'teacher/css/index.css' %}">
</head>
<body>
    <div>
        <h2>我是第{{ num }}次访问浏览器</h2>
        <h3 style="color:lightblue">
            teacher首页面
        </h3>
        <p>当前时间：{{ now|date:"Y年m月d日 H:i:s" }}</p>
        <p>列表：{{ lt|first }}</p>
        <p>相加：{{ lt.0|add:1.2}}</p>
        <p>相减：{{ lt.1|add:-2.2}}</p>
        <p>相连：{{ lt.1|add:"a"|default:"something"}}</p>
        <p>字典：{{ dt }}</p>
        <p>函数：{{ func }}</p>
        <p>js: {{ js }}</p>
{#        <p>{{ js|safe }}</p>#}
        {% now_time %}
        <table>
            <tr>
                <th>序号</th>
                <th>性别</th>
                <th>年龄</th>
                <th>性别</th>
            </tr>
            <tr>
                <td>1</td>
                <td>{{ students.0.name }}</td>
                <td>{{ students.0.age }}</td>
                <td>{{ students.0.sex }}</td>
            </tr>
            <tr>
                <td>2</td>
                <td>{{ students.1.name }}</td>
                <td>{{ students.1.age }}</td>
                <td>{{ students.1.sex }}</td>
            </tr>
            <tr>
                <td>3</td>
                <td>{{ students.2.name }}</td>
                <td>{{ students.2.age }}</td>
                <td>{{ students.2.sex }}</td>
            </tr>
            <tr>
                <td>4</td>
                <td>{{ students.3.name }}</td>
                <td>{{ students.3.age }}</td>
                <td>{{ students.3.sex }}</td>
            </tr>
        </table>
        <table>
            <tr>
                <th>序号</th>
                <th>性别</th>
                <th>年龄</th>
                <th>性别</th>
                <th>qq</th>
                <th>电话</th>
                <th>创建时间</th>
            </tr>

            {% for i in students %}
                <tr {% if i.sex == 0 %} style="color:red"{% endif %}>
                    <td><a href="{% url 'teacher:detail' i.name %}">{{ forloop.counter }}</a></td>
                    <td>{{ i.name }}</td>
                    <td>{{ i.age }}</td>
                    <td>{{ i.sex|to_sex:"en" }}</td>
                    <td>{{ i.qq }}</td>
                    <td>{{ i.phone }}</td>
                    <td>{{ i.create_time }}</td>
{#                    <td>{{ i.course }}</td>#}
{#                    <td>#}
{#                        {% show_list i.course  style='button'%}#}
{#                    </td>#}
                </tr>
            {% endfor %}
        </table>
    </div>
    <div style="position:fixed; bottom: 20px; right: 10px; background-color: #7ab5d3">
        {%  include 'teacher/ad.html' %}
    </div>
</body>
</html>

templates/teacher/index_new.html
{% extends 'teacher/base.html' %}
{% load static %}
{% block title %}首页面{% endblock %}
{% block link %}
    <link rel="stylesheet" href="{% static 'teacher/css/index.css' %}">
{% endblock %}
{% block content %}
    <style type="text/css">
        body {
            padding-top: 40px;
            padding-bottom: 40px;
            background-color: #f5f5f5;
        }

        .form-signin {
            max-width: 300px;
            padding: 19px 29px 29px;
            margin: 0 auto 20px;
            background-color: #fff;
            border: 1px solid #e5e5e5;
            -webkit-border-radius: 5px;
            -moz-border-radius: 5px;
            border-radius: 5px;
            -webkit-box-shadow: 0 1px 2px rgba(0, 0, 0, .05);
            -moz-box-shadow: 0 1px 2px rgba(0, 0, 0, .05);
            box-shadow: 0 1px 2px rgba(0, 0, 0, .05);
        }

        .form-signin .form-signin-heading,
        .form-signin .checkbox {
            margin-bottom: 10px;
        }

        .form-signin input[type="text"],
        .form-signin input[type="password"] {
            font-size: 16px;
            height: auto;
            margin-bottom: 15px;
            padding: 7px 9px;
        }

    </style>
    <div class="container">

        <form class="form-signin">

            <h2 class="form-signin-heading">Please sign in</h2>
            <input type="text" class="input-block-level" placeholder="Email address">
            <input type="password" class="input-block-level" placeholder="Password">
            <label class="checkbox">
                <input type="checkbox" value="remember-me"> Remember me
            </label>
            <button class="btn btn-large btn-primary" type="submit">Sign in</button>
        </form>
        <div style="position:fixed; bottom: 20px; right: 10px; background-color: #7ab5d3">
            {% include 'teacher/ad.html' %}
        </div>
    </div>
{% endblock %}

templates/teacher/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Sign in &middot; Twitter Bootstrap</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
{#    <link href="../assets/css/bootstrap.css" rel="stylesheet">#}
      <link rel="stylesheet" href="{% static 'teacher/css/login.css' %}">
    <style type="text/css">
      body {
        padding-top: 40px;
        padding-bottom: 40px;
        background-color: #f5f5f5;
      }

      .form-signin {
        max-width: 300px;
        padding: 19px 29px 29px;
        margin: 0 auto 20px;
        background-color: #fff;
        border: 1px solid #e5e5e5;
        -webkit-border-radius: 5px;
           -moz-border-radius: 5px;
                border-radius: 5px;
        -webkit-box-shadow: 0 1px 2px rgba(0,0,0,.05);
           -moz-box-shadow: 0 1px 2px rgba(0,0,0,.05);
                box-shadow: 0 1px 2px rgba(0,0,0,.05);
      }
      .form-signin .form-signin-heading,
      .form-signin .checkbox {
        margin-bottom: 10px;
      }
      .form-signin input[type="text"],
      .form-signin input[type="password"] {
        font-size: 16px;
        height: auto;
        margin-bottom: 15px;
        padding: 7px 9px;
      }

    </style>
    <link href="../assets/css/bootstrap-responsive.css" rel="stylesheet">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="../assets/js/html5shiv.js"></script>
    <![endif]-->

    <!-- Fav and touch icons -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../assets/ico/apple-touch-icon-114-precomposed.png">
      <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../assets/ico/apple-touch-icon-72-precomposed.png">
                    <link rel="apple-touch-icon-precomposed" href="../assets/ico/apple-touch-icon-57-precomposed.png">
                                   <link rel="shortcut icon" href="../assets/ico/favicon.png">
  </head>

  <body>

    <div class="container">

        <!--
        1. action 指定提交地址，如果不写或者为空，表示提交到当前页
        2. method: 用来指定提交方式，默认使用GET
         -->
      <form class="form-signin" method="post">
          {% csrf_token %}
        <h2 class="form-signin-heading">Please sign in</h2>
        <p>用户名：<input type="text" class="input-block-level" placeholder="Email address" name="username"></p>
        <p>密码：<input type="password" class="input-block-level" placeholder="Password" name="password" ></p>
        <label class="checkbox">
          <input type="checkbox" value="remember-me"> Remember me
        </label>
        <button class="btn btn-large btn-primary" type="submit">Sign in</button>
      </form>
        <div style="position:fixed; bottom: 20px; right: 10px; background-color: #7ab5d3">
        {%  include 'teacher/ad.html' %}
    </div>

    </div> <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
{#    <script src="../assets/js/jquery.js"></script>#}
{#    <script src="../assets/js/bootstrap-transition.js"></script>#}
{#    <script src="../assets/js/bootstrap-alert.js"></script>#}
{#    <script src="../assets/js/bootstrap-modal.js"></script>#}
{#    <script src="../assets/js/bootstrap-dropdown.js"></script>#}
{#    <script src="../assets/js/bootstrap-scrollspy.js"></script>#}
{#    <script src="../assets/js/bootstrap-tab.js"></script>#}
{#    <script src="../assets/js/bootstrap-tooltip.js"></script>#}
{#    <script src="../assets/js/bootstrap-popover.js"></script>#}
{#    <script src="../assets/js/bootstrap-button.js"></script>#}
{#    <script src="../assets/js/bootstrap-collapse.js"></script>#}
{#    <script src="../assets/js/bootstrap-carousel.js"></script>#}
{#    <script src="../assets/js/bootstrap-typeahead.js"></script>#}

  </body>
</html>

templates/teacher/showList.html
{#<ul>#}
{#    {% for c in ls %}#}
{#        <li>{{ c }}</li>#}
{#    {% endfor %}#}
{#</ul>#}

{% for c in ls %}
    {% if style == 'button' %}
        <div class="list-group">
            <button type="button" class="list-group-item">{{ c }}</button>
        </div>
    {% elif style == 'link' %}
        <div class="list-group">
            <a href="#" class="list-group-item">{{ c }}</a>
        </div>
    {% else %}
        <ul class="list-group">
            <li class="list-group-item">
                {{ c }}
            </li>
        </ul>
    {% endif %}
{% endfor %}

templates/teacher/upload.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <!-- enctype 上传多个文件-->
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="file" name="file"， multiple="multiple">
        <input type="submit" value="上传">
    </form>
</body>
</html>

templates/teacher/uploade.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <!-- inctype 上传多个文件-->
    <form action="" method="post">
        <input type="file" name="file">
        <input type="submit" value="上传">
    </form>
</body>
</html>